#!/bin/bash

UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)

lastlog=$(last -1  $USER | head -1 | cut -c 23- | sed 's/ \+/ /g')
sysload=$(uptime | sed 's/,//g' | grep -ohe 'load average[s:][: ].*' | awk '{ print $3" (1 min) "$4" (5 min) "$5" (15 min)" }')
mem=$(free -m | sed -n 2p | awk '{ print "Total: "$2"MB Used: "$3"MB Free: "$4"MB" }')
processes=$(top -b -n 1 | sed -n 2p | sed 's/,//g' | awk {'print $2" "$3" "$4" "$5" "$6" "$7""'})

hostname=$(cat /etc/hostname)
echo "========== $hostname =========="

cat << EOF

CPU: `cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2`
Distro: `lsb_release -s -d` with `uname -r`

EOF

# Print Output
echo -en "\e[35mPublic IP.....:\e[0m \e[36m`ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`\e[0m\n"
echo -en "\e[35mLast Login....:\e[0m \e[36m$lastlog\e[0m\n"
echo -en "\e[35mUptime........:\e[0m \e[36m$UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINUTES minutes\e[0m\n"
echo -en "\e[35mProcesses.....:\e[0m \e[36m$processes\e[0m\n"
echo -en "\e[35mLoad..........:\e[0m \e[36m$sysload\e[0m\n"
echo -en "\e[35mMemory MB.....:\e[0m \e[36m$mem\e[0m\n"
echo -en "\e[35mSwap Available:\e[0m \e[36m`free -m | tail -n 1 | awk {'print $4"MB of "$2"MB"'}`\e[0m\n"
echo -en "\e[35mDisk Available:\e[0m \e[36m`df -h / | sed -n 2p | awk '{ print $4" of "$2" ("$5" used)" }'`\e[0m\n"
echo " "
echo "Checking for updates..."
apt-get -s dist-upgrade | grep "^[[:digit:]]\+ upgraded"
