#!/bin/bash
#
# Script to open multiple tabs in gnome terminal and automatically reattach screen session
#
# Replace entries in the `hosts` array with the servers you need to connect to regularly
#
# @author webworker01
#

hosts=(
'host1'
'host2'
'etc'
)

for host in "${hosts[@]}"; do
    gnome-terminal --tab --title="${host}" -- bash -ic "ssh -t ${host} 'screen -rd'"
done
