#!/bin/bash
# Sets up "night mode" and lowers brightness (software based) for desktop
#
# 3 presets:
#   default - slight dim and slight redshift
#   night   - very dim and very redshift
#   off     - normal desktop settings
#
# @see https://askubuntu.com/a/1061304

# set -x

night() {
    xrandr --listmonitors 2>/dev/null | grep ": +" | while read line; do
        display=$(awk '{print $4}' <<< $line)
        xrandr --output $display --gamma $1 --brightness $2 2>/dev/null
    done
}

case $1 in
    off|reset|normal) night 1:1:1       1.0 ;;
    night)            night 1.2:0.8:0.5 0.45 ;;
    *)                night 1.1:0.8:0.5 0.7 ;;
esac
